name:                typing-game
version:             0.1.0.0
github:              "piotr-lewandowski/typing-game"
license:             BSD3
author:              "Piotr Lewandowski"
maintainer:          "Piotr Lewandowski"
copyright:           "2023 Piotr Lewandowski"

extra-source-files:
- README.md

description: Simple typing game written in Haskell

dependencies:
- base >= 4.7 && < 5
- microlens
- microlens-th
- Yampa
- aeson
- bytestring

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  typing-game-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - typing-game
    - yampa-gloss
    - gloss
    - JuicyPixels
    - gloss-juicy

tests:
  typing-game-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - typing-game
    - hspec
    - QuickCheck
